# ezdyn Dashboard (USA): Smets-Wouters (2007) + curated Pfeifer DSGE_mod NK models
#
# Run the dashboard via app.R, not this file directly - app.R sources this
# file and calls usa_dashboard() with the working directory set correctly
# (paths below are relative to this file's own directory; see the cwd note
# further down).
#
# Multi-model ezdyn dashboard combining the Smets-Wouters (2007) replication
# model with 7 curated small-scale New Keynesian models from the Pfeifer
# DSGE_mod collection (https://github.com/JohannesPfeifer/DSGE_mod, cloned
# into dashboard/DSGEModDash/DSGE_mod - see README.md for setup), each of
# which has an active monetary policy shock suitable for impulse-response
# policy exercises. Mirrors dashboard/DINGOdash/dingo_dashboard.R's structure
# (paths, timeline, config, a single `usa_dashboard()` function), but with no
# custom help content, HSD preamble, or baseline prepare/extend hooks -
# everything else stays at ezdyn's generic defaults.
#
# Inputs (dashboard/DSGEModDash/inputs/) are generated by build_new_models.m
# (Dynare JSON + the real usmodel_data.mat estimation sample as CSV for SW)
# and build_model_metadata.R (variable/shock/parameter metadata). Paths below
# are relative to this file's own directory (this dashboard must be
# launched/sourced with that as the working directory - see app.R).
#
# Display names are shared across models wherever the underlying concept and
# units match (e.g. "Nominal Interest Rate", "Inflation", "Hours Worked" are
# used by SW and several of the 7 new models alike) - this is what lets the
# Impulse Response Library overlay the same variable's response across
# models. `optimal_policy` below still targets SW only (as before) - the 7
# new models are lightweight textbook models without a natural single choice
# of policy-relevant loss variables, so Optimal Policy is left un-configured
# for them; they are fully usable in the Overview/Impulse Response Library/
# Alternative Paths tabs regardless.
#
# TODO: Historical Shock Decomposition's date axis and units need fixing -
# ez_hd()'s `t` is a raw period index, not yet mapped onto real calendar
# quarters, and the bar/line values aren't yet confirmed against this
# model's metadata units.
#
# The 7 curated Pfeifer models are calibrated (never estimated/smoothed), so
# they have no real historical shock decomposition data (no
# `oo_$SmoothedShocks`/`SmoothedVariables`) - only Smets Wouters (2007) can
# actually support the Historical Shock Decomposition tab.
# `configure_dashboard()`'s `hsd$models` now filters automatically to only
# models with genuine shock decomposition data, so this file doesn't need to
# restrict it explicitly - only Smets Wouters (2007) is selectable there.
# TODO: variable-level filtering within a model still relies on the
# metadata-curated `hsd` column (`defined_display_names(hsd_only = TRUE)`),
# not a genuine-data check.

library(dplyr)
library(tibble)

sw_dynare_path <- "inputs/SW_2007_45.json"
sw_metadata_path <- "inputs/variable_metadata.xlsx"
sw_historical_path <- "inputs/usmodel_data.csv"

# The 7 additional curated Pfeifer NK models (see build_new_models.m /
# build_model_metadata.R). Each entry names the model in the dashboard,
# gives it a distinct plot colour, and points at its JSON/metadata inputs.
dsgemoddash_extra_models <- tribble(
  ~model_name,                  ~colour,          ~dynare_path,                            ~metadata_path,
  "Gali NK (Ch.3)",             "steelblue",      "inputs/Gali2015Ch3.json",               "inputs/Gali2015Ch3_metadata.xlsx",
  "Gali NK+Wage (Ch.6)",        "darkorange",     "inputs/Gali2015Ch6.json",               "inputs/Gali2015Ch6_metadata.xlsx",
  "Gali SOE (Ch.8)",            "purple",         "inputs/Gali2015Ch8.json",               "inputs/Gali2015Ch8_metadata.xlsx",
  "Gali Unemployment (2010)",   "firebrick",      "inputs/Gali2010.json",                  "inputs/Gali2010_metadata.xlsx",
  "Ireland (2004)",             "darkgoldenrod",  "inputs/Ireland2004.json",               "inputs/Ireland2004_metadata.xlsx",
  "Ascari-Sbordone (2014)",     "darkslategray",  "inputs/AscariSbordone2014.json",        "inputs/AscariSbordone2014_metadata.xlsx",
  "Born-Pfeifer (2018)",        "deeppink",       "inputs/BornPfeifer2018MP.json",         "inputs/BornPfeifer2018MP_metadata.xlsx"
)


# The real Smets-Wouters (2007) US estimation sample (usmodel_data.mat, fed to
# the model with prefilter=0) runs 1947Q3-2004Q4 (230 quarters). Matching this
# dashboard's end-of-quarter date labelling convention (a quarter's Date is
# the first day of its LAST month, e.g. a Q3 value is dated "-09-01"), the
# first observation is dated 1947-09-01.
sw_historical_start <- as.Date("1947-09-01")

sw_timeline <- list(
  data_start = sw_historical_start,
  data_end = as.Date("2004-12-01"),
  forecast_start = as.Date("2002-09-01"),
  forecast_end = as.Date("2004-12-01")
)
# Optimal Policy needs a longer commitment horizon than the main timeline;
# the baseline is built out to this date so `extend_baseline` can stay at its
# default (identity).
sw_optimal_policy_forecast_end <- as.Date("2014-06-01")

# Build the dashboard baseline: each metadata variable's own steady-state
# level, flat over every supplied quarter, with the real 1947Q3-2004Q4
# estimation sample overwritten in wherever it overlaps. There's no real data
# for the model-consistent (non-observable) variables or beyond 2004Q4, so
# those stay at steady state.
sw_build_baseline <- function(model, dates) {
  steady_state <- as.numeric(model$oo_$dr$ys)
  names(steady_state) <- model$M_$endo.names

  varmeta <- model$M_$varmeta
  # `scale_factor` is a list column (one value per row, see calc_scale_factors()
  # in rescale_irf.R) - unlist() it to a plain numeric vector before use.
  values <- steady_state[varmeta$dynare_name] * unlist(varmeta$scale_factor)
  names(values) <- varmeta$display_name

  baseline <- tibble(date = dates, !!!as.list(values))

  historical <- read.csv(sw_historical_path) |>
    as_tibble() |>
    mutate(date = seq(sw_historical_start, by = "quarter", length.out = dplyr::n())) |>
    rename(
      `Output Growth` = dy,
      `Consumption Growth` = dc,
      `Investment Growth` = dinve,
      `Hours Worked` = labobs,
      `Inflation` = pinfobs,
      `Real Wage Growth` = dw,
      `Nominal Interest Rate` = robs
    )

  dplyr::rows_update(baseline, historical, by = "date")
}

# Read each of the 7 additional metadata variables' own steady-state level
# off its model's Dynare solution and repeat it flat over every supplied
# quarter - a synthetic baseline with no invented economic scenario, since
# these textbook models have no real-world data counterpart (mirrors SW's own
# steady-state expansion above, minus the historical overlay).
dsgemoddash_build_synthetic_baseline <- function(model, dates) {
  steady_state <- as.numeric(model$oo_$dr$ys)
  names(steady_state) <- model$M_$endo.names

  varmeta <- model$M_$varmeta
  values <- steady_state[varmeta$dynare_name] * unlist(varmeta$scale_factor)
  names(values) <- varmeta$display_name

  tibble(date = dates, !!!as.list(values))
}

# Left-join `extra` onto `base` by date, keeping only display-name columns
# not already present in `base`. Several of the 7 additional models share
# display names with SW (e.g. "Nominal Interest Rate", "Inflation", "Hours
# Worked") - SW's real historical values should win for those, so each new
# model's own (always-zero-or-steady-state) column is dropped in favour of
# whatever the combined baseline already has.
dsgemoddash_merge_new_columns <- function(base, extra) {
  new_cols <- setdiff(names(extra), names(base))
  if (length(new_cols) == 0) {
    return(base)
  }
  dplyr::left_join(base, extra[, c("date", new_cols)], by = "date")
}

# Build and return the combined dashboard `shiny.appobj`.
usa_dashboard <- function() {
  sw_model <- ezdyn::read_dynare(
    path = sw_dynare_path,
    path_meta = sw_metadata_path,
    model_name = "Smets Wouters (2007)",
    colour = "forestgreen"
  )

  extra_models <- purrr::pmap(dsgemoddash_extra_models, function(model_name, colour, dynare_path, metadata_path) {
    ezdyn::read_dynare(
      path = dynare_path,
      path_meta = metadata_path,
      model_name = model_name,
      colour = colour
    )
  })
  names(extra_models) <- dsgemoddash_extra_models$model_name

  models <- c(list(`Smets Wouters (2007)` = sw_model), extra_models)

  # `import_baseline()`'s `translate_baseline()` step only recognizes columns
  # matching ITS OWN `source_model`'s metadata (columns from other models are
  # dropped with a warning) - so each model's baseline must be translated
  # separately (against `models = models` for full cross-model unit
  # validation) and then merged, rather than built as one combined data frame
  # translated against a single source model.
  baseline_dates <- seq(sw_timeline$data_start, sw_optimal_policy_forecast_end, by = "quarter")
  sw_baseline_df <- sw_build_baseline(sw_model, baseline_dates)
  baseline <- ezdyn::import_baseline(input = sw_baseline_df, source_model = sw_model, models = models)
  for (extra_model in extra_models) {
    extra_baseline_df <- dsgemoddash_build_synthetic_baseline(extra_model, baseline_dates)
    extra_baseline <- ezdyn::import_baseline(input = extra_baseline_df, source_model = extra_model, models = models)
    baseline <- dsgemoddash_merge_new_columns(baseline, extra_baseline)
  }

  config <- ezdyn::configure_dashboard(
    name = "ezdyn Dashboard (USA)",
    models = models,
    timeline = sw_timeline,
    baselines = list(`US estimation sample` = baseline),
    default_baseline = "US estimation sample",
    instrument_display_name = "Nominal Interest Rate",
    instrument_shock_name = "Monetary policy shock",
    irf = list(defaults = list(display_names = "Inflation", horizon = 20)),
    # The 7 curated Pfeifer NK models remain selectable for Alternative Paths
    # (they share "Nominal Interest Rate"/"Monetary policy shock" with SW),
    # but only Smets Wouters (2007) is selected by default - it is the only
    # model with a real historical baseline; the others use synthetic
    # steady-state baselines.
    alt_paths = list(defaults = list(models = "Smets Wouters (2007)")),
    optimal_policy = list(
      policy_model = "Smets Wouters (2007)",
      instrument_variable = "robs",
      instrument_shock = "em",
      forecast_end = sw_optimal_policy_forecast_end,
      loss_variable_choices = c(
        "Inflation" = "pinfobs",
        "Output growth" = "dy",
        "Nominal interest rate" = "robs",
        "Wage growth" = "dw"
      ),
      constraint_variable_choices = c(
        "Nominal interest rate" = "robs",
        "Inflation" = "pinfobs"
      ),
      default_response_variables = c("robs", "pinfobs", "dy"),
      default_loss_variables = c("pinfobs", "dy")
    )
  )

  ezdyn::ezdyn_dashboard(config)
}
